# Generated by Django 3.2.16 on 2022-11-16 14:32

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221116_1729'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Нельзя',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('author')), _negated=True), name='no_self_subscribe'),
        ),
    ]
