# Generated by Django 3.2.16 on 2022-11-19 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221118_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Некорретное имя пользователя.', regex='^[\\w.@+-]+\\Z')], verbose_name='Логин'),
        ),
    ]
